### ISSUE TITLE
`capng_apply` does not notice it failed to apply a capability

### ISSUE THREAD

**Issue by snarkmaster** [stevegrubb/libcap-ng#19]
A complete ready-to-go repro is here:
https://gist.github.com/snarkmaster/4d019ab39e9adbe4fd7269f4f9812692

The short story is this:
 - start with full capabilities -- the last byte of the bounding set in `/proc/PID/status` is `ff`
 - run `capsh --drop=cap_chown --` -- the last byte is now `fe`
 - under the `capsh run a `libcap-ng` program which tries to set the bounding set to full again
 - `capng_apply` succeeds
 - after applying, run `capng_have_capability(CAPNG_BOUNDING_SET, CAP_CHOWN)` -- the result is 1
 - but if I look at `procfs`, the last byte still ends in `fe` (of course).

**Comment by stevegrubb** [comment]
Not sure a satisfactory solution exists for this. As you know, bounding set bits can only be dropped. So, there's not a call that will fail. But we can re-sync the bounding set in memory with what the kernel has so that its at least accurate. IOW, capng_apply will succeed, but the test above will fail. I also added some documentation saying not to do that.

**Comment by snarkmaster** [comment]
I understand that bits in the bounding set cannot be dropped. It's just as a user, I would most naively expect "success" to represent "we did exactly what you asked for", while "failure" can be "partial failure" or "complete failure".

In my use-case I'm blithely trying to clone capabilities, and whether this **can** succeed or not depends on the setting in which the `clonecaps` utility is used. Lucky for me, I'm only using it in a setting where I know my bounding set is a superset of the target's.

I also understand if you want the success / failure to represent the lack of errors returned by the kernel. In that case, maybe enhancing the `man` page to explain that a "success" return code does not mean that you got exactly the caps you added?

Or, alternately, what about making `capng_update` fail if the user tries to add bits to the bounding set? That would also get the "intuitive" behavior that I mention above.

Thanks for re-syncing the bounding set. Does `libcap-ng` internally also use the bounding set as a bitmask? If not, do you have to re-sync the other caps that the bounding set masks?

**Comment by stevegrubb** [comment]
No, cap-ng does not use the bounding set as a mask. We don't need to resync other capabilities because capset will return an error if you can't do something. And the ambient capabilities have a set or drop option so we can be accurate on that one, too. So, it's really the bounding set that is unique.

**Comment by snarkmaster** [comment]
Ok, that's fair. So what do you think of the two API improvements I proposed?
 - `capng_update` fails if a user is trying to add bits to the bounding set?
 - `capng_apply` fails if the `procfs` bounding set doesn't match what we asked for?

**Comment by stevegrubb** [comment]
Well, during capng_update, we don't know enough about anything to fail. Suppose the capabilities are intended for a file. There are no bounding sets for files. So, anyone can play with these as much as they want because it doesn't matter. During capng_apply/capng_change_id would be more reasonable. But it would require keeping a second copy around in a size independent way and having comparison routines...which don't currently exist.

**Comment by stevegrubb** [comment]
Closing this issue. 0.8.4 was released yesterday unpatched on Fedora. (Had to carry a patch logging it would fail instead of failing.) That should finally finish this issue. Thanks for reporting it.
